// ============================================================
// SOC2 Prebuilt Policy — Categorized Blueprint (5 Trust Principles)
// ============================================================

import { Rule, PolicyCategory } from '../types';

export const SOC2_POLICY_NAME = 'SOC2 Compliance Pack';
export const SOC2_POLICY_TYPE = 'soc2';

export const SOC2_CATEGORIES: PolicyCategory[] = [
    {
        id: 'security',
        name: 'Security (Common Criteria)',
        description: 'Protection against unauthorized access, disclosure, or damage.',
    },
    {
        id: 'availability',
        name: 'Availability',
        description: 'Systems are available for operation and use as committed.',
    },
    {
        id: 'confidentiality',
        name: 'Confidentiality',
        description: 'Information designated as confidential is protected as committed.',
    },
    {
        id: 'integrity',
        name: 'Processing Integrity',
        description: 'System processing is complete, valid, accurate, and authorized.',
    },
    {
        id: 'privacy',
        name: 'Privacy',
        description: 'Personal information is collected, used, retained, disclosed, and disposed of.',
    },
];

export const SOC2_RULES: Rule[] = [
    {
        rule_id: 'SOC2-CC6.1-001',
        name: 'Logical Access Control (MFA)',
        type: 'access',
        severity: 'CRITICAL',
        threshold: null,
        time_window: null,
        conditions: { field: 'mfa_enabled', operator: 'equals', value: false },
        policy_excerpt: 'Access to sensitive data must be protected by multi-factor authentication.',
        policy_section: 'CC6.1 — Logical Access Security',
        is_active: true,
        category: 'security',
        description: 'Identify accounts with access to PII that do not have MFA enabled.',
        historical_context: {
            avg_fine: '$4.88M (Average cost of credential-based breach)',
            breach_example: 'Uber 2022 — Contractor account without MFA allowed internal network pivot.',
            article_reference: 'CC6.1',
        },
    },
    {
        rule_id: 'SOC2-CC6.1-002',
        name: 'Tenant Data Isolation',
        type: 'access',
        severity: 'CRITICAL',
        threshold: null,
        time_window: null,
        conditions: { field: 'tenant_id', operator: 'equals', value: 'MISMATCH' },
        policy_excerpt: 'Customer data must be logically isolated from other customers.',
        policy_section: 'CC6.1 — Logical Access Security',
        is_active: true,
        category: 'integrity',
        description: 'Check for rows in a customer export that contain data from other tenants.',
        historical_context: {
            avg_fine: '$3.5M (Average fine for cross-tenant data leak)',
            breach_example: 'SaaS provider leaked private reports to competitors due to query logic error.',
            article_reference: 'CC6.1',
        },
    },
    {
        rule_id: 'SOC2-CC6.7-001',
        name: 'Encryption of Data at Rest',
        type: 'encryption',
        severity: 'HIGH',
        threshold: null,
        time_window: null,
        conditions: { field: 'is_encrypted', operator: 'equals', value: false },
        policy_excerpt: 'The entity protects confidential information during its processing lifecycle.',
        policy_section: 'CC6.7 — Protection of Information',
        is_active: true,
        category: 'confidentiality',
        description: 'Identify databases or tables containing PII stored in plaintext.',
        historical_context: {
            avg_fine: '$18M (British Airways breach — lack of security measures)',
            breach_example: 'Unencrypted S3 buckets exposed 100M+ user records in plain text.',
            article_reference: 'CC6.7',
        },
    },
    {
        rule_id: 'SOC2-CC7.1-001',
        name: 'Audit Trail & Logging',
        type: 'access',
        severity: 'HIGH',
        threshold: null,
        time_window: null,
        conditions: { field: 'has_audit_log', operator: 'equals', value: false },
        policy_excerpt: 'Monitoring activities must be performed to identify anomalies.',
        policy_section: 'CC7.1 — System Monitoring',
        is_active: true,
        category: 'security',
        description: 'Identify administrative actions or data access events not captured in audit logs.',
        historical_context: {
            avg_fine: '$1.2M (Cost increase when detection/containment exceeds 200 days)',
            breach_example: 'Company unable to determine extent of breach due to disabled database logs.',
            article_reference: 'CC7.1',
        },
    },
    {
        rule_id: 'SOC2-CC9.1-001',
        name: 'Business Continuity (Backups)',
        type: 'access',
        severity: 'HIGH',
        threshold: null,
        time_window: null,
        conditions: { field: 'last_backup_age_hours', operator: 'greater_than', value: 24 },
        policy_excerpt: 'The entity protects the system against environmental risks.',
        policy_section: 'CC9.1 — Business Continuity',
        is_active: true,
        category: 'availability',
        description: 'Alert when critical data has not been backed up in the last 24 hours.',
        historical_context: {
            avg_fine: '$5.1M (Average cost of ransomware data loss)',
            breach_example: 'Cloud service provider lost 2 weeks of customer data during cluster failure.',
            article_reference: 'CC9.1',
        },
    },
    {
        rule_id: 'SOC2-CC6.2-001',
        name: 'Credential Leakage Detection',
        type: 'access',
        severity: 'CRITICAL',
        threshold: null,
        time_window: null,
        conditions: { field: 'contains_secrets', operator: 'equals', value: true },
        policy_excerpt: 'Controls should prevent unauthorized use of credentials.',
        policy_section: 'CC6.2 — User Access Management',
        is_active: true,
        category: 'security',
        description: 'Detect API keys, passwords, or secret tokens stored in non-secure database columns.',
        historical_context: {
            avg_fine: '$2M (Average cost of secret key exposure in public repositories/DBs)',
            breach_example: 'Twitter 2023 — Private keys leaked in source code allowed API takeover.',
            article_reference: 'CC6.2',
        },
    },
    {
        rule_id: 'SOC2-CC6.3-001',
        name: 'Termination of Access',
        type: 'access',
        severity: 'MEDIUM',
        threshold: null,
        time_window: null,
        conditions: { field: 'is_active_user', operator: 'equals', value: false },
        policy_excerpt: 'Access is modified or terminated in a timely manner.',
        policy_section: 'CC6.3 — User Access Modification',
        is_active: true,
        category: 'security',
        description: 'Identify records where an "inactive" or "terminated" user still has active write permissions.',
        historical_context: {
            avg_fine: '$150k (Common administrative fine for failed access reviews)',
            breach_example: 'Terminated employee used valid credentials to delete production databases.',
            article_reference: 'CC6.3',
        },
    },
    {
        rule_id: 'SOC2-CC5.2-001',
        name: 'Data Residency Compliance',
        type: 'format',
        severity: 'MEDIUM',
        threshold: null,
        time_window: null,
        conditions: { field: 'region_mismatch', operator: 'equals', value: true },
        policy_excerpt: 'Entity communicates privacy objectives to internal and external parties.',
        policy_section: 'CC5.2 — Communication and Information',
        is_active: true,
        category: 'confidentiality',
        description: 'Verify that EU customer data is not being processed or stored in unauthorized regions.',
        historical_context: {
            avg_fine: '€1.2B (Meta — transferring data to US without valid basis)',
            breach_example: 'French health data host fined for using non-EU cloud providers without consent.',
            article_reference: 'CC5.2',
        },
    },
    {
        rule_id: 'SOC2-P1.1-001',
        name: 'Data Retention Policy',
        type: 'retention',
        severity: 'MEDIUM',
        threshold: null,
        time_window: null,
        conditions: { field: 'age_years', operator: 'greater_than', value: 7 },
        policy_excerpt: 'Personal information is retained for only as long as necessary.',
        policy_section: 'P1.1 — Privacy Criteria',
        is_active: true,
        category: 'privacy',
        description: 'Identify data that has exceeded the standard 7-year legal retention period.',
        historical_context: {
            avg_fine: '$1M (Sears — retaining customer tracking data post-consent withdrawal)',
            breach_example: 'Startup failing audit because "Deleted Users" table still contained full PII from 2016.',
            article_reference: 'P1.1',
        },
    },
];
